---
title: "Untitled"
output: pdf_document
date: "`r Sys.Date()`"
---

```{r warning=FALSE}
library(readr)
library(dplyr)
library(ggplot2)
library(ggridges)
```


```{r}
adult <- read_csv("./data/adult.data", col_names = FALSE)
colnames(adult) <- c("age", "workclass", "fnlwgt", "education", "education_num",
                     "marital_status", "occupation", "relationship", "race",
                     "sex", "capital_gain", "capital_loss", "hours_per_week",
                     "native_country", "income")

adult$occupation <- ifelse(adult$occupation == "?", "Unknown", adult$occupation)
adult$workclass <- ifelse(adult$workclass == "?", "Unknown", adult$workclass)
adult$native_country <- ifelse(adult$native_country == "?", "Unknown", adult$native_country)
adult$income <- ifelse(adult$income == "<=50K", 0, 1)

adult$workclass <- as.factor(adult$workclass)
adult$education <- as.factor(adult$education)
adult$marital_status <- as.factor(adult$marital_status)
adult$occupation <- as.factor(adult$occupation)
adult$relationship <- as.factor(adult$relationship)
adult$race <- as.factor(adult$race)
adult$sex <- as.factor(adult$sex)
adult$native_country <- as.factor(adult$native_country)
adult$income <- as.factor(adult$income)

adult <- adult %>%
  select(-fnlwgt, -education_num)
```


```{r}
create_plot <- function(data, var_name, type = "prop") {
  if (type == "count") {
    position <- "stack"
    colors <- c("1" = "#4CAF50", "0" = "#E4381B")
  } else {
    position <- "fill"
    colors <- c("1" = "#4CAF50", "0" = "#F44336")
  }

  ggplot(data, aes(x = .data[[var_name]], fill = income)) +
    geom_bar(position = position) +
    scale_fill_manual(values = colors) +
    labs(x = var_name, y = "", fill = "income") +
    theme_minimal() +
    theme(
      axis.text.x = element_text(angle = 45, hjust = 1),
      legend.position = "none"
    )
}
```



```{r}
summary(adult)
```

```{r}
table(adult$workclass)
```

```{r}
table(adult$education)
```

```{r}
table(adult$marital_status)
```

```{r}
table(adult$occupation)
```
```{r}
table(adult$relationship)
```

```{r}
table(adult$race)
```

```{r}
table(adult$sex)
```

```{r}
adult %>%
  filter(native_country == "South") %>%
  ggplot(aes(x = race, fill = race)) +
  geom_bar() +
  theme_minimal()
```


```{r}
table(adult$native_country)
```

```{r}
adult <- adult %>%
  mutate(region = case_when(
    native_country %in% c("Canada", "United-States", "Mexico", "Cuba", 
                          "Dominican-Republic", "Jamaica", "Puerto-Rico", 
                          "Haiti", "Guatemala", "Honduras", "Nicaragua", 
                          "El-Salvador", "Trinadad&Tobago", 
                          "Outlying-US(Guam-USVI-etc)") ~ "North America",
    
    native_country %in% c("Columbia", "Ecuador", "Peru") ~ "South America",
    
    native_country %in% c("England", "France", "Germany", "Greece", 
                          "Holand-Netherlands", "Hungary", "Ireland", 
                          "Italy", "Poland", "Portugal", "Scotland", 
                          "Yugoslavia") ~ "Europe",
    
    native_country %in% c("Cambodia", "China", "Hong", "India", "Iran", 
                          "Japan", "Laos", "Philippines", "Taiwan", 
                          "Thailand", "Vietnam") ~ "Asia",
    
    native_country == "South" ~ "Other/Unknown",
    
    TRUE ~ "Other/Unknown"
  ))


adult$age_category <- cut(adult$age, 
                         breaks = c(0, 25, 35, 45, 55, 65, Inf),
                         labels = c("0-24", "25-34", "35-44", "45-54", "55-64", "65+"),
                         right = FALSE)

adult <- adult %>%
  mutate(education_category = case_when(
    education %in% c('1st-4th', '5th-6th') ~ 'Primary',
    education %in% c('7th-8th', 'HS-grad', '10th', '11th', '12th', '9th') ~ 'Secondary',
    education %in% c('Some-college', 'Bachelors', 'Assoc-voc', 'Assoc-acdm') ~ 'Tertiary',
    education %in% c('Masters', 'Doctorate', 'Prof-school') ~ 'Advanced',
    TRUE ~ 'Other'
  ))

adult$education_category <- factor(adult$education_category, 
                                   levels = c("Primary", "Secondary", "Tertiary", "Advanced", "Other"))

adult <- adult %>%
  mutate(marital_category = case_when(
    marital_status %in% c("Married-civ-spouse", "Married-AF-spouse", "Married-spouse-absent") ~ "Married",
    marital_status %in% c("Divorced", "Separated", "Widowed") ~ "Not Married",
    marital_status == "Never-married" ~ "Never Married",
    TRUE ~ "Other"
  ))

adult <- adult %>%
  mutate(occupation_group = case_when(
    occupation %in% c("Tech-support", "Craft-repair", "Other-service", 
                      "Sales", "Exec-managerial", "Protective-serv", 
                      "Priv-house-serv") ~ "Service/Tech",
    
    occupation %in% c("Prof-specialty", "Adm-clerical", 
                      "Armed-Forces") ~ "Professional/Admin",
    
    occupation %in% c("Machine-op-inspct", "Transport-moving", 
                      "Farming-fishing", "Handlers-cleaners") ~ "Manual Labor",
    
    occupation %in% c("Unknown") ~ "Unknown",
    
    TRUE ~ "Other"
  ))


```

```{r}
adult %>%
  group_by(education_category, marital_category, sex, occupation_group) %>%
  summarise(n = n()) %>%
  arrange(n)
```
Idomus yra tas kuris profesonalas su pradiniu issilavinimu :D, siulau 'other' ir 'unknow' isvis mest lauk, ju mazai ir nieko gero is ju

```{r}
table(adult$income)
```
"0" apie 3 kartus daugiau  nei "1". Šitą problemą spręsti reiks arba slenkstį koreguojant, 
arba generuojant papildomai duomenų mokymo aibei.

```{r}
create_plot(adult, "workclass", type = "count")
```

```{r}
create_plot(adult, "workclass", type = "prop")
```

```{r}
ggplot(adult, aes(x = income, y = age, fill = income)) +
    geom_boxplot() +
    theme_minimal()
```

```{r}
ggplot(adult, aes(x = income, y = capital_gain, fill = income)) +
    geom_boxplot() +
    theme_minimal()
```
Žiauru. Taip atrodo ištrinus:
```{r}
ggplot(adult, aes(x = income, y = capital_loss, fill = income)) +
    geom_boxplot() +
    theme_minimal()
```

```{r}
ggplot(adult, aes(x = income, y = hours_per_week, fill = income)) +
    geom_boxplot() +
    theme_minimal()
```




```{r}
ggplot(adult, aes(x = capital_gain, y = income, fill = income)) +
  geom_density_ridges(alpha = 0.7)
  theme_ridges() + 
  theme(legend.position = "none")
```

```{r}
ggplot(adult, aes(x = capital_loss, y = income, fill = income)) +
  geom_density_ridges(alpha = 0.7)
  theme_ridges() + 
  theme(legend.position = "none")
```

```{r}
ggplot(adult, aes(x = age, y = income, fill = income)) +
  geom_density_ridges(alpha = 0.7)
  theme_ridges() + 
  theme(legend.position = "none")
```


```{r}
ggplot(adult, aes(x = hours_per_week, y = income, fill = income)) +
  geom_density_ridges(alpha = 0.7)
  theme_ridges() + 
  theme(legend.position = "none")
```

```{r}
adult %>%
  group_by(workclass, education, marital_status,occupation,relationship,race,sex) %>%
  summarise(n = n()) %>%
  arrange(n)
```

